services:
  backend:
    build:
      context: ./backend
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - ALLOWED_HOSTS=http://localhost:3000,http://localhost:5173
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - STAGE=production
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
    container_name: react-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    # stdin_open: true
    # tty: true

